### ISSUE TITLE
Header includes unnecessary nav element

### ISSUE THREAD

**Issue by DarrickFauvel** [DarrickFauvel/fem-skills-elearning-landing-page#11]
Description: In index.html, the header has a populated nav element that is not required.

Steps to Reproduce: In a web browser, view index.html.

Expected Behavior: There should not be a list of nav links in the header.

Actual Behavior: A list of navigation links appears.

Environment: n/a

Screenshots or Code:
![image](https://github.com/DarrickFauvel/fem-skills-elearning-landing-page/assets/76695983/50f02b94-fb03-4bc4-a356-b7dfe080dbfb)

```html
<header>
  <img src="./assets/logo-dark.svg" alt="Dark Logo" />
  <nav>
    <ul>
      <li><a href="#">Home</a></li>
      <li><a href="#">Courses</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </nav>
  <a href="#">Get Started</a>
</header>
```

The code should simply be:
```html
<header>
  <img src="./assets/logo-dark.svg" alt="Dark Logo" />
  <a href="#">Get Started</a>
</header>
```

Reproducibility: n/a

Context: The design specification does not have a navigation menu.

**Comment by semsi-dogruer** [comment]
I took care of this issue.
