### ISSUE TITLE
Add CSS Stylesheet to index.html

### ISSUE THREAD

**Issue by DarrickFauvel** [DarrickFauvel/fem-skills-elearning-landing-page#2]
**Description**: Create a stylesheet file and link it to index.html

**Steps to Reproduce**: n/a

**Expected Behavior**: n/a

**Actual Behavior**: n/a

**Environment**: n/a

**Screenshots or Code**:
```html
<link rel="stylesheet" href="style.css">
```

**Reproducibility**: n/a

**Context**: We can't do this project without CSS.

**Comment by DarrickFauvel** [comment]
Semsi, please pull down the latest develop branch and create a new branch for this issue.

**Comment by semsi-dogruer** [comment]
I took care of this issue.
